services:
  - type: web
    name: event-management
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: MONGODB_URI
        sync: false
      - key: AUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        sync: false
